# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: "Default"

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Set-Location C:\agents\_work\3\s'
- task: AzureCLI@2
  inputs:
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'Connect-AzAccount'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Connect-AzAccount'
    
- task: AzurePowerShell@5
  inputs:
    ScriptType: 'InlineScript'
    Inline: 'Connect-AzAccount'
    azurePowerShellVersion: 'LatestVersion'
  
#- task: PowerShell@2
 # inputs:
  #  filePath: './AzDeployScript.ps1'

