# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: "Default"

steps:

- task: AzurePowerShell@4
  displayName: Do important stuff
  inputs:
    connectedServiceNameARM: '$(AzDoServiceConnectionName)'
    scriptType: 'FilePath'
    scriptPath: './DoImportantStuff.ps1'
    scriptArguments: '-ImportantDirectory "$(ImportantDirectory)"'
    errorActionPreference: 'stop'
    failOnStandardError: true
    azurePowerShellVersion: 'LatestVersion'

#- task: PowerShell@2
 # inputs:
  #  filePath: './AzDeployScript.ps1'
  #- task: PowerShell@2
  #inputs:
   # targetType: 'inline'
    #script: 'Set-Location C:\agents\_work\3\s'

